server:
  port: 8080
spring:
  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:testdb
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/load?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  h2:
    console:
      path: /h2-console
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: /yjh/upload
logging.level:
  org.hibernate.SQL: debug