apiVersion: apps/v1
kind: Deployment
metadata:
  name: fc-loan
spec:
  selector:
    matchLabels:
      app: fc-loan
    template:
      metadata:
        labels:
          app: fc-loan
      spec:
        containers:
          - name: fc-loan
            image: fc-loan
            ports:
              - containerPort: 8080