apiVersion: v1
kind: Service
metadata:
  name: fc-loan
  namespace: default
  labels:
    app: fc-loan
spec:
  selector:
    app: fc-loan
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer